In [2]:
import numpy as np

In [3]:
survey = np.loadtxt('survey.txt', dtype= 'int')  # here we read the data
survey

array([ 7, 10,  5, ...,  5,  9, 10])

 # 1. Does the loaded file returns an array of survey score?

yes it return 1D Array and the shape of array (1167,)

 # 2. Find the length of the returned array.

In [4]:
length=len(survey)

In [5]:
print("the length of the returned array :",length)

the length of the returned array : 1167


# 3. Perform aggregate operations - min, max, sum

In [6]:
# here , we find min of the returned array
m = min(survey)
print(f" min of the  {survey} is :",m)

 min of the  [ 7 10  5 ...  5  9 10] is : 1


In [7]:
# here , we find max of the returned array
maximum = max(survey)
print(f" max of the { survey} is :",maximum)

 max of the [ 7 10  5 ...  5  9 10] is : 10


In [8]:
# here , we find sum of the returned array
s = sum(survey)
print(f"sum of the {survey} :",s)

sum of the [ 7 10  5 ...  5  9 10] : 8461


# 4 Let Survey score greater than 6 is known as promoter score. Display the promoter score.

In [10]:
promoter_score = survey[survey>6]
promoter_score

array([ 7, 10,  9,  9,  7,  9,  9,  9, 10,  9,  9,  7, 10,  9,  7,  9,  9,
        9,  8,  9,  9,  9, 10, 10,  9, 10,  9, 10,  9,  9, 10, 10,  9,  8,
       10,  8,  9, 10,  7, 10, 10,  9,  9, 10, 10, 10,  9, 10,  7,  9, 10,
        9,  9,  7,  9, 10,  9,  9,  9,  9,  9,  9,  8, 10,  8,  7,  9,  9,
        8,  8,  9, 10,  9, 10,  9,  9,  8,  8,  9,  9,  9, 10, 10,  9,  7,
       10,  9,  9, 10,  7,  9,  7,  9, 10,  8,  9,  9,  7,  7,  9,  9,  9,
        7,  8,  9,  9,  7,  9,  9,  9,  8,  9, 10,  8,  9,  9,  9,  9,  7,
        9,  9,  9,  9, 10,  9,  9,  9,  9,  9,  8,  8,  8, 10,  7, 10,  9,
       10,  8, 10, 10,  7,  8,  8, 10,  9, 10,  9,  9,  7,  9,  9,  9,  9,
        9, 10,  9, 10,  8,  9, 10,  9, 10, 10, 10,  7,  9,  9, 10,  8,  7,
       10,  9,  9,  7,  8,  9,  9, 10,  8,  8,  9,  9,  9,  7,  9, 10,  7,
       10,  9,  9,  9,  8, 10,  9,  9,  9,  9,  9, 10,  9,  8,  9,  8,  9,
       10,  9,  7, 10,  7, 10,  9,  9,  7,  8,  9,  9,  7,  7, 10,  9,  8,
       10,  7,  9,  7,  9

# 5. Let Survey score less than 6 is known as detractor score. Display the detractor score.

In [12]:
detractor_score = survey[survey<6]
detractor_score

array([5, 4, 4, 5, 1, 5, 5, 1, 4, 5, 4, 4, 4, 5, 1, 4, 1, 4, 1, 5, 5, 1,
       1, 4, 1, 5, 4, 1, 1, 4, 1, 5, 1, 4, 4, 1, 1, 1, 1, 1, 1, 1, 4, 1,
       1, 5, 5, 5, 4, 4, 1, 4, 1, 4, 1, 5, 1, 1, 5, 4, 4, 4, 4, 1, 4, 5,
       4, 4, 1, 1, 5, 5, 1, 5, 1, 5, 5, 4, 5, 4, 1, 1, 1, 1, 4, 1, 4, 4,
       5, 4, 1, 1, 1, 1, 5, 4, 5, 5, 4, 1, 5, 1, 4, 4, 1, 1, 1, 4, 4, 5,
       5, 4, 5, 5, 5, 1, 4, 1, 5, 5, 1, 5, 1, 1, 5, 5, 4, 4, 1, 4, 4, 4,
       1, 1, 4, 4, 4, 5, 5, 1, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 5, 4, 4,
       5, 1, 4, 5, 5, 5, 1, 5, 4, 1, 1, 5, 5, 5, 4, 5, 4, 4, 1, 4, 4, 4,
       4, 5, 1, 5, 5, 1, 4, 4, 5, 1, 1, 4, 5, 5, 5, 1, 4, 5, 5, 4, 1, 5,
       5, 5, 1, 1, 5, 5, 1, 1, 1, 4, 5, 5, 4, 4, 4, 5, 1, 4, 1, 4, 5, 4,
       5, 5, 1, 5, 1, 5, 5, 1, 4, 5, 5, 4, 1, 5, 1, 4, 1, 4, 1, 1, 1, 1,
       1, 1, 4, 1, 5, 4, 5, 1, 5, 1, 5, 4, 4, 4, 4, 5, 5, 1, 4, 1, 5, 5,
       1, 4, 1, 1, 4, 4, 4, 4, 1, 4, 1, 1, 4, 1, 5, 4, 1, 1, 5, 4, 5, 4,
       4, 4, 1, 5, 5, 1, 4, 5, 4, 4, 4, 1, 4, 1, 4,

# 6.Calculate the promoter and detractor percentage.

In [18]:
per_promoter = (len(promoter_score)/len(survey))*100
per_promoter

71.55098543273351

In [19]:
per_detractor = (len(detractor_score)/len(survey))*100
per_detractor

28.449014567266495

# notee:- if we want to check the our calculated percentage right or wrong :=
we add both variables and we see our result is equal to 100 so, our calculated percentage is right. if not equal to 100 ,its wrong