In [3]:
import numpy as np

# 1. Load and visualize the dataset.

In [4]:
fit = np.loadtxt('fit.txt',dtype='object')
fit

array([['06-10-2017', '5464', 'Neutral', '181', '5', 'Inactive'],
       ['07-10-2017', '6041', 'Sad', '197', '8', 'Inactive'],
       ['08-10-2017', '25', 'Sad', '0', '5', 'Inactive'],
       ['09-10-2017', '5461', 'Sad', '174', '4', 'Inactive'],
       ['10-10-2017', '6915', 'Neutral', '223', '5', 'Active'],
       ['11-10-2017', '4545', 'Sad', '149', '6', 'Inactive'],
       ['12-10-2017', '4340', 'Sad', '140', '6', 'Inactive'],
       ['13-10-2017', '1230', 'Sad', '38', '7', 'Inactive'],
       ['14-10-2017', '61', 'Sad', '1', '5', 'Inactive'],
       ['15-10-2017', '1258', 'Sad', '40', '6', 'Inactive'],
       ['16-10-2017', '3148', 'Sad', '101', '8', 'Inactive'],
       ['17-10-2017', '4687', 'Sad', '152', '5', 'Inactive'],
       ['18-10-2017', '4732', 'Happy', '150', '6', 'Active'],
       ['19-10-2017', '3519', 'Sad', '113', '7', 'Inactive'],
       ['20-10-2017', '1580', 'Sad', '49', '5', 'Inactive'],
       ['21-10-2017', '2822', 'Sad', '86', '6', 'Inactive'],
       ['22-10

# Append the elements in list from fit dataset using for loop

In [5]:
list=[]
list_1=[]
list_2=[]
list_3=[]
list_4=[]
list_5=[]
for i in fit:
    list.append(i[0])
    list_1.append(int(i[1]))
    list_2.append(i[2])
    list_3.append(int(i[3]))
    list_4.append(int(i[4]))
    list_5.append(i[5])
    


 # 2. What is the average step count across the dataset?

In [6]:
m= sum(list_1)/len(list_1) # we find mean(average) without numpy array funtion
m

2935.9375

In [7]:
step_count = np.array(list_1) # here we convert list into array

In [8]:
avg = np.mean(step_count)
print(f"average step count across the dataset is:- {avg}")

average step count across the dataset is:- 2935.9375


 # 3. On which date did the person burn the most calories, and what was their mood on that day?

In [9]:
calories_burned=np.array(list_3)
calories_burned

array([181, 197,   0, 174, 223, 149, 140,  38,   1,  40, 101, 152, 150,
       113,  49,  86,   6,  99, 143, 125, 129,   6,   9,  10,  72, 150,
       141, 156,  57,  72,  17, 181, 197, 131, 154, 137, 193,  19, 101,
       139, 164, 137,  22,  17,   9, 145, 192, 146, 234, 167,  16,  17,
        32,  35, 220, 116,  23,  44, 131,  86, 194,  60, 121,  76,  93,
        53,  25, 227, 125, 243,  14,  39,  55, 158,   7, 213, 116, 129,
        21,  28,  16, 180, 138, 176,  99,   5,   1,  10,  47,  84,  23,
         4,   0,   0,   0,   0])

In [10]:
max_calories = np.max(calories_burned) # we find maximum calories_burned
max_calories_index = np.argmax(calories_burned) # we find index of maximum calories_burned
date =list[max_calories_index]
mood =list_2[max_calories_index]
print(f"Most calories burned on {date} with mood : {mood}")


Most calories burned on 14-12-2017 with mood : Happy


# 4. How many days does the dataset show the person being "Active" vs. "Inactive"?

In [11]:
active_count =list_5.count('Active')
inactive_count =list_5.count('Inactive')

In [12]:
print(f"person being Active {active_count} days")

person being Active 42 days


In [13]:
print(f"person being Inactive {inactive_count} days")

person being Inactive 54 days


# 5. Which mood is associated with the highest average calories burned?

In [14]:
mood = np.array(list_2)
mood


array(['Neutral', 'Sad', 'Sad', 'Sad', 'Neutral', 'Sad', 'Sad', 'Sad',
       'Sad', 'Sad', 'Sad', 'Sad', 'Happy', 'Sad', 'Sad', 'Sad', 'Sad',
       'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral',
       'Happy', 'Neutral', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Neutral', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Neutral',
       'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Neutral', 'Sad', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Happy', 'Happy', 'Sad', 'Neutral', 'Neutral',
       'Sad', 'Sad', 'Neutral', 'Neutral', 'Happy', 'Neutral', 'Neutral',
       'Sad', 'Neutral', 'Sad', 'Neutral', 'Neutral', 'Sad', 'Sad', 'Sad',
       'Sad', 'Happy', 'Neutral', 'Happy', 'Neutral', 'Sad', 'Sad', 'Sad',
       'Neutral', 'Neutral', 'Sad', 'Sad', 'Happy', 'Neutral', 'Neutral',
       'Happy'], dtype='<U7')

In [15]:
calories_burned

array([181, 197,   0, 174, 223, 149, 140,  38,   1,  40, 101, 152, 150,
       113,  49,  86,   6,  99, 143, 125, 129,   6,   9,  10,  72, 150,
       141, 156,  57,  72,  17, 181, 197, 131, 154, 137, 193,  19, 101,
       139, 164, 137,  22,  17,   9, 145, 192, 146, 234, 167,  16,  17,
        32,  35, 220, 116,  23,  44, 131,  86, 194,  60, 121,  76,  93,
        53,  25, 227, 125, 243,  14,  39,  55, 158,   7, 213, 116, 129,
        21,  28,  16, 180, 138, 176,  99,   5,   1,  10,  47,  84,  23,
         4,   0,   0,   0,   0])

In [26]:
matrix = np.array([mood , calories_burned] , dtype='object')

print("Mood: ", matrix[0])
print("calories_burned :",(matrix[1]))

Mood:  ['Neutral' 'Sad' 'Sad' 'Sad' 'Neutral' 'Sad' 'Sad' 'Sad' 'Sad' 'Sad' 'Sad'
 'Sad' 'Happy' 'Sad' 'Sad' 'Sad' 'Sad' 'Neutral' 'Neutral' 'Neutral'
 'Neutral' 'Neutral' 'Neutral' 'Happy' 'Neutral' 'Happy' 'Happy' 'Happy'
 'Happy' 'Happy' 'Happy' 'Happy' 'Neutral' 'Happy' 'Happy' 'Happy' 'Happy'
 'Happy' 'Happy' 'Happy' 'Happy' 'Happy' 'Happy' 'Neutral' 'Happy' 'Happy'
 'Happy' 'Happy' 'Happy' 'Happy' 'Happy' 'Happy' 'Happy' 'Neutral' 'Sad'
 'Happy' 'Happy' 'Happy' 'Happy' 'Happy' 'Happy' 'Happy' 'Sad' 'Neutral'
 'Neutral' 'Sad' 'Sad' 'Neutral' 'Neutral' 'Happy' 'Neutral' 'Neutral'
 'Sad' 'Neutral' 'Sad' 'Neutral' 'Neutral' 'Sad' 'Sad' 'Sad' 'Sad' 'Happy'
 'Neutral' 'Happy' 'Neutral' 'Sad' 'Sad' 'Sad' 'Neutral' 'Neutral' 'Sad'
 'Sad' 'Happy' 'Neutral' 'Neutral' 'Happy']
calories_burned : [181 197 0 174 223 149 140 38 1 40 101 152 150 113 49 86 6 99 143 125 129
 6 9 10 72 150 141 156 57 72 17 181 197 131 154 137 193 19 101 139 164 137
 22 17 9 145 192 146 234 167 16 17 32 35 220 116 2

In [17]:
Mean_0 = np.mean(calories_burned[mood=='Happy'])
print(f"Happy mood is associated with the calories burned {Mean_0}")
print()
Mean_1=np.mean(calories_burned[mood=='Sad'])
print(f"sad mood is associated with the calories burned {Mean_1}")
print()
Mean_2=np.mean(calories_burned[mood=='Neutral'])
print(f"Neutral mood is associated with the calories burned {Mean_2}")

Happy mood is associated with the calories burned 108.55

sad mood is associated with the calories burned 67.72413793103448

Neutral mood is associated with the calories burned 98.70370370370371


In [18]:
matrix_0=np.array([Mean_0 , Mean_1 ,Mean_2],dtype='int')
matrix_0

array([108,  67,  98])

In [29]:
result= np.sort(matrix_0)
result

array([ 67,  98, 108])

In [30]:
print(f"Happy mood is associated with the highest average calories burned {Mean_0}")

Happy mood is associated with the highest average calories burned 108.55
